import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import GlobalBackground from "@/components/GlobalBackground";
import GradualBlur from "@/components/GradualBlur";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-transparent" suppressHydrationWarning>
        <GlobalBackground />
        
        {/* Global Fading Edges */}
        <GradualBlur 
          preset="page-header" 
          height="4rem" 
          zIndex={-10} 
          style={{ background: 'linear-gradient(to bottom, rgba(0,0,0,1), rgba(0,0,0,0))' }}
        />
        <GradualBlur 
          preset="page-footer" 
          height="4rem" 
          zIndex={-10} 
          style={{ background: 'linear-gradient(to top, rgba(0,0,0,1), rgba(0,0,0,0))' }}
        />
        
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
