import type { Metadata } from "next";
import { Outfit, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import GlobalBackground from "@/components/GlobalBackground";
import GradualBlur from "@/components/GradualBlur";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-transparent" suppressHydrationWarning>
        <GlobalBackground />
        
        {/* Global Fading Edges (Bottom Only, Small & Smooth) */}
        <GradualBlur 
          target="page" 
          position="bottom" 
          height="2.5rem" 
          strength={2}
          divCount={8}
          exponential={true}
          curve="bezier"
          zIndex={-10} 
        />
        
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
